---
title: "USCOVID19Analysis"
author: "hollen"
date: "3/27/2020"
output: html_document
params:
  debug: 0
  usStateData: 'data/us-states.csv'
  usCountyData: 'data/us-counties.csv'
  dataSource: 'Data provided by the N.Y. Times [https://github.com/nytimes/covid-19-data]'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## U.S. COVID-19 Analysis from Aggregated New York Times Data

This is just a sandbox for me to evaluate the COVID-19 data that has been aggregated by the New York Times, which is available at the following GitHub location  <https://github.com/nytimes/covid-19-data>.

Per the license agreement for the data I would like to provide the link to the U.S. tracking page for the New York Times as <https://www.nytimes.com/interactive/2020/us/coronavirus-us-cases.html>


```{r Initialize, echo=FALSE, warning=FALSE, error=FALSE}
library(tidyverse)
library(ggplot2)
library(knitr)
```


```{r InputDataAndCleanUp, echo=FALSE, warning=FALSE, error=FALSE}
dfStateData <- read.csv(file=params$usStateData)
dfStateData <- dfStateData %>%
  mutate(Date=date, State=state, FIPS=fips, Cases=cases, Deaths=deaths) %>%
  mutate(Day=as.integer(date)) %>%
  select(-date, -state, -fips, -cases, -deaths)
if(params$debug==1) head(dfStateData)
```

```{r dfDailyCountyCases, echo=FALSE, warning=FALSE, error=FALSE}
dfCountyData <- read.csv(file=params$usCountyData)
dfCountyData <- dfCountyData %>%
  mutate(Date=date, County=county, State=state, FIPS=fips, Cases=cases, Deaths=deaths) %>%
  mutate(Day=as.integer(date)) %>%
  select(-date, -county, -state, -fips, -cases, -deaths)
if(params$debug==1) head(dfCountyData)
```

```{r dfDailyStateCases, echo=FALSE, warning=FALSE, error=FALSE}
dfDailyStateCases <- dfStateData %>%
  group_by(Day) %>%
  summarise(DailyStateCases=sum(Cases, na.rm=TRUE))
if(params$debug==1) head(dfDailyStateCases)
```

```{r dfDailyMichiganCases, echo=FALSE, warning=FALSE, error=FALSE}
dfDailyMichiganCases <- dfStateData %>%
  filter(State == 'Michigan') %>%
  group_by(Day) %>%
  summarize(DailyMichiganCases=sum(Cases, na.rm=TRUE))
if(params$debug==1) head(dfDailyMichiganCases)
```

```{r dfDailyCasesGraphic, echo=FALSE, warning=FALSE, error=FALSE}
dfDailyStateCases %>%
  ggplot(mapping=aes(Day, DailyStateCases)) +
  geom_line(colour = 'cyan') +
  coord_cartesian() + 
  theme_dark() + 
  labs(y='Daily Cases', x='Day', title='Daily U.S. Cases', subtitle=params$dataSource)
```
```{r dfDailyMichiganCasesGraphic, echo=FALSE, warning=FALSE, error=FALSE}
dfDailyMichiganCases %>%
  ggplot(mapping=aes(Day, DailyMichiganCases)) +
  geom_line(colour = 'lightgreen') +
  coord_cartesian() + 
  theme_dark() + 
  labs(y='Daily Cases', x='Day', title='Daily Michigan Cases', subtitle=params$dataSource)
```

```{r dfDailyLocalCountiesCases, echo=FALSE, warning=FALSE, error=FALSE}
dfDailyLocalCountiesCases <- dfCountyData %>% 
  filter(State == 'Michigan') %>% 
  group_by(County) %>% 
  summarize(CasesPerCounty=sum(Cases, na.rm=TRUE), DeathsPerCounty=sum(Deaths, na.rm=TRUE)) %>% 
  arrange(desc(CasesPerCounty)) %>%
  top_n(15)
if(params$debug==1) head(dfDailyLocalCountiesCases)
kable(dfDailyLocalCountiesCases)
```

```{r df24HourChange, echo=FALSE, warning=FALSE, error=FALSE}
dfMichiganChange <- dfCountyData %>% 
  filter(Date == as.character(Sys.Date()-1)) %>% 
  filter(State=='Michigan') %>% 
  group_by(County) %>% 
  summarize(CurrentCasesPerCounty=sum(Cases, na.rm=TRUE), CurrentDeathsPerCounty=sum(Deaths, na.rm=TRUE)) %>% 
  arrange(County)
if(params$debug==1) head(dfMichiganChange)

dfPreviousDayReportData <- dfCountyData %>% 
  filter(Date == as.character(Sys.Date()-2)) %>% 
  filter(State=='Michigan') %>% 
  group_by(County) %>% 
  summarize(PreviousCasesPerCounty=sum(Cases, na.rm=TRUE), PreviousDeathsPerCounty=sum(Deaths, na.rm=TRUE)) %>% 
  arrange(County)
if(params$debug==1) head(dfPreviousDayReportData)

dfMichiganDelta <- dfMichiganChange %>% full_join(dfPreviousDayReportData, by='County')

dfMichiganDelta <- dfMichiganDelta %>%
  mutate(CasesPctChange=round((CurrentCasesPerCounty-PreviousCasesPerCounty)/CurrentCasesPerCounty*100, digits = 0)) %>%
  mutate(DeathsPctChange=round((CurrentDeathsPerCounty-PreviousDeathsPerCounty)/CurrentDeathsPerCounty*100, digits = 0)) %>% 
  mutate_at(vars(CasesPctChange, DeathsPctChange), ~replace(., is.nan(.), '-')) %>%
  mutate_at(vars(CasesPctChange, DeathsPctChange), ~replace(., is.infinite(.), '-')) %>%
  arrange(desc(CurrentCasesPerCounty)) %>%
  top_n(15)
  
kable(dfMichiganDelta, 
      col.names=c('County', 'CasesToday', 'DeathsToday', 'CasesYesterday', 'DeathsPrevious', 'CasesChg[%]', 'DeathsChg[%]'),
      align=c('lcccccc'))
```

